// src/component/common/Login.tsx
import { useForm } from "react-hook-form";

const Login = () => {
    const {
        register,
        handleSubmit,
        formState: { errors, isValid },
    } = useForm({ mode: "onChange" });

    const onSubmit = (data: any) => {
        console.log("Form submitted:", data);
        // Handle authentication here
    };

    return (
        <div className="flex min-h-[85vh] bg-gray-500 mx-[5%] mt-[1.6%]">
            {/* Login card */}
            <div className="flex-1 max-w-[564px] p-8 flex flex-col justify-center bg-white shadow-lg">
                {/* Optional logo */}
                {/* <div className="text-center mb-4">
          <img src="images/logo.jpeg" alt="USCIB Logo" className="mx-auto max-w-[120px]" />
        </div> */}

                {/* Optional welcome title */}
                {/* <h2 className="text-center text-[#597b7c] mb-2 text-xl font-semibold">
          Welcome to USCIB Carnet Portal!
        </h2> */}

                <h3 className="text-center text-gray-600 text-base mb-8">
                    ATA Carnet: Your Passport for Duty-Free Global Trade
                </h3>

                <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-6">
                    <div>
                        <label className="block mb-1 text-gray-700">Username</label>
                        <div className="relative">
                            <input
                                {...register("username", { required: true })}
                                className="w-full border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring focus:ring-blue-200"
                                placeholder="Enter username"
                            />
                            <span className="absolute right-3 top-2.5 text-gray-400">
                                <i className="fas fa-user"></i>
                            </span>
                        </div>
                        {errors.username && (
                            <p className="text-red-600 text-sm mt-1">Username is required</p>
                        )}
                    </div>

                    <div>
                        <label className="block mb-1 text-gray-700">Password</label>
                        <div className="relative">
                            <input
                                type="password"
                                {...register("password", { required: true })}
                                className="w-full border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring focus:ring-blue-200"
                                placeholder="Enter password"
                            />
                            <span className="absolute right-3 top-2.5 text-gray-400">
                                <i className="fas fa-lock"></i>
                            </span>
                        </div>
                        {errors.password && (
                            <p className="text-red-600 text-sm mt-1">Password is required</p>
                        )}
                    </div>

                    <div className="text-right -mt-4">
                        <a href="#" className="text-sm text-gray-600 hover:underline">
                            Forgot your password?
                        </a>
                    </div>

                    <button
                        type="submit"
                        disabled={!isValid}
                        className="bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition disabled:opacity-50"
                    >
                        Sign In
                    </button>

                    {/* Optional error message */}
                    {/* <p className="text-center text-red-600 mt-2">Invalid credentials</p> */}
                </form>
            </div>

            {/* Info section */}
            <div className="flex-1 p-16 bg-[#597b7c] text-white flex flex-col justify-center max-md:hidden">
                <h3 className="text-3xl mb-6 font-bold">ATA Carnet</h3>
                <p className="text-base leading-relaxed mb-4">
                    Also known as the "Merchandise Passport," is an international customs document that simplifies
                    temporary exports to over 79 countries and territories. It allows businesses to explore new
                    markets, showcase products at trade shows, and attend global conferences without paying duties
                    or taxes.
                </p>
                <p className="text-base leading-relaxed">
                    It simplifies customs procedures for the temporary movement of goods and allows goods to enter
                    Customs territories of the ATA Carnet system free of customs duties and taxes for up to one
                    year.
                </p>
            </div>
        </div>
    );
};

export default Login;

// src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../core/services/auth.service';
import { CommonModule } from '@angular/common';
import { AngularMaterialModule } from '../shared/module/angular-material.module';
import { UserService } from '../core/services/user.service';

@Component({
  selector: 'app-login',
  imports: [ReactiveFormsModule, CommonModule, AngularMaterialModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {
  loginForm: FormGroup;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private userService: UserService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    if (this.userService.isLoggedIn()) {
      this.router.navigate(['/home']);
    }
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      const { username, password } = this.loginForm.value;

      this.authService.login(username, password).subscribe({
        next: (response) => {
          this.isLoading = false;
          if (response?.msg) {
            this.userService.setUser(username);
            this.router.navigate(['/home']);
          } else {
            this.errorMessage = response?.error ?? response?.msg;
          }
        },
        error: (error) => {
          this.isLoading = false;
          this.errorMessage = 'Invalid username or password';
          console.error('Login error:', error);
        }
      });
    }
  }
}
<div class="login-container">
    <div class="login-card">
        <div class="logo-container">
            <img src="images/logo.jpeg" alt="USCIB Logo" class="logo">
        </div>

        <h2 class="welcome-title">Welcome to USCIB Carnet Portal!</h2>
        <h3 class="subtitle">ATA Carnet: Your Passport for Duty-Free Global Trade</h3>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
            <mat-form-field appearance="outline">
                <mat-label>Username</mat-label>
                <input matInput formControlName="username" required>
                <mat-icon matSuffix>person</mat-icon>
                <mat-error *ngIf="loginForm.get('username')?.errors?.['required']">
                    Username is required
                </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline">
                <mat-label>Password</mat-label>
                <input matInput type="password" formControlName="password" required>
                <mat-icon matSuffix>lock</mat-icon>
                <mat-error *ngIf="loginForm.get('password')?.errors?.['required']">
                    Password is required
                </mat-error>
            </mat-form-field>

            <div class="forgot-password">
                <a href="#" class="forgot-link">Forgot your password?</a>
            </div>

            <button mat-raised-button color="primary" type="submit" [disabled]="!loginForm.valid">
                Sign In
            </button>

            <mat-error class="error-message" *ngIf="errorMessage !== ''">
                {{errorMessage}}
            </mat-error>
        </form>
    </div>

    <div class="info-section">
        <h3>ATA Carnet</h3>
        <p>
            Also known as the "Merchandise Passport," is an international customs document that simplifies temporary
            exports to over 79 countries and territories.
            It allows businesses to explore new markets, showcase products at trade shows, and attend global conferences
            without paying duties or taxes.
        </p>
        <p>
            It simplifies customs procedures for the temporary movement of goods and allows goods to
            enter Customs territories of the ATA Carnet system free of customs duties and taxes for up to
            one year.
        </p>
    </div>
</div>
